package interfaz;

import basededatos.iEncargado_de_compras;

public class Encargado_de_compras {
	public iEncargado_de_compras _iEncargado_de_compras;
	public Ver_listado_de_compras__Encargado_de_compras_ _ver_listado_de_compras__Encargado_de_compras_;
}