package interfaz;

import basededatos.iUsuario_no_registrado;

public class Usuario_no_registrado extends Común_Usuarios {
	public iUsuario_no_registrado _iUsuario_no_registrado;
	public Buscar_producto _buscar_producto;
	public Visualizar_anuncios _visualizar_anuncios;
	public Visualizar_producto__Usuario_no_registrado_ _visualizar_producto__Usuario_no_registrado_;
	public Ver_carrito__Usuario_no_registrado_ _ver_carrito__Usuario_no_registrado_;
}