package interfaz;

import vistas.VistaVerlistadodecompras;

public class Ver_listado_de_compras__Encargado_de_compras_ extends VistaVerlistadodecompras {
	public Encargado_de_compras _encargado_de_compras;
	public Pedidos__Encargado_de_compras_ _pedidos__Encargado_de_compras_;
}